### ISSUE TITLE
Use video as input

### ISSUE THREAD

**Issue by akamob** [xerifg/GaitRecognition#1]
Hi, Thank you for the great work.

When I run `python GaitDemoV1.py`, I got:
```
Traceback (most recent call last):
  File "GaitDemoV1.py", line 301, in <module>
    window = GaitDemo()
  File "GaitDemoV1.py", line 50, in __init__
    self.capture = rsd.DepthCamera()  # through D435 camera
  File "/home/lk3696/GaitRecognition/realsense_depth.py", line 12, in __init__
    pipeline_profile = config.resolve(pipeline_wrapper)
RuntimeError: No device connected
```
Based on my application, I hope I can record videos and use these files as inputs.

May i have your suggestions to achieve it?
Any help is much appreciated:)

**Comment by xerifg** [comment]
> Hi, Thank you for the great work.
> 
> When I run `python GaitDemoV1.py`, I got:
> 
> ```
> Traceback (most recent call last):
>   File "GaitDemoV1.py", line 301, in <module>
>     window = GaitDemo()
>   File "GaitDemoV1.py", line 50, in __init__
>     self.capture = rsd.DepthCamera()  # through D435 camera
>   File "/home/lk3696/GaitRecognition/realsense_depth.py", line 12, in __init__
>     pipeline_profile = config.resolve(pipeline_wrapper)
> RuntimeError: No device connected
> ```
> 
> Based on my application, I hope I can record videos and use these files as inputs.
> 
> May i have your suggestions to achieve it? Any help is much appreciated:)

cap = cv2.VideoCapture('/path/to/your/video.mp4') 
ret, frame = cap.read()
self.capture = frame

maybe you can try this

**Comment by akamob** [comment]
Hi, thank you for quick response:)

I modified the code according to your suggestions, and I got:
```
Traceback (most recent call last):
  File "GaitDemoV1.py", line 308, in <module>
	window = GaitDemo()
  File "GaitDemoV1.py", line 66, in __init__
	self.detector = ptk.PoseDetector()
  File "/home/lk3696/GaitRecognition/PoseTrackingModel.py", line 19, in __init__
	self.Pose = self.mppose.Pose(self.model, self.model_comple, self.smooth_lm, self.segmentation,
TypeError: __init__() takes from 1 to 6 positional arguments but 8 were given
```

May I have your suggestions to fix this problem? Any help is much appreciated:)

**Comment by akamob** [comment]
Hi, @xerifg, I have solved the above problem I mentioned, but I met new problem:
```
Traceback (most recent call last):
  File "GaitDemoV1.py", line 185, in play
	mask = self.detector.results.segmentation_mask  # dtype:float32
AttributeError: type object 'SolutionOutputs' has no attribute 'segmentation_mask'
```
Could you please provide the definitions of `segmentation_mask`?

Any help is much appreciated:)

**Comment by xerifg** [comment]
> Hi, @xerifg, I have solved the above problem I mentioned, but I met new problem:
> 
> ```
> Traceback (most recent call last):
>   File "GaitDemoV1.py", line 185, in play
> 	mask = self.detector.results.segmentation_mask  # dtype:float32
> AttributeError: type object 'SolutionOutputs' has no attribute 'segmentation_mask'
> ```
> 
> Could you please provide the definitions of `segmentation_mask`?
> 
> Any help is much appreciated:)

you can update mediapipe version, you can find segmentation_mask in the latest version

**Comment by akamob** [comment]
Hi, @xerifg, Thank you very much for your reply.

Now I can run your project, but it shows these messages:
![mess](https://user-images.githubusercontent.com/49118957/164886768-4b569645-7114-44e2-9e31-2b3367e835e9.png)

Could you give me some suggestions to fix this problem and let me know what cause this to happen?
Any help is much appreciated:)

**Comment by xerifg** [comment]
> 

congratulations!!!，it is just a simple demo,i will be very happy that you can upgrate it.
The problem you met is ok,it just because you are so close to your camera,the demo can't capture all keypoints(33 keypoints)

**Comment by akamob** [comment]
Hi, @xerifg, Thank you!

About upgrade, I'm wondering if it is possible that use keypoints of human body for gait recognition to distinguish human identity?

If yes, Could you give me some suggestions to find methods so that I can achieve this goal?

Any help is much appreciated:)

**Comment by xerifg** [comment]
> Hi, @xerifg, Thank you!
> 
> About upgrade, I'm wondering if it is possible that use keypoints of human body for gait recognition to distinguish human identity?
> 
> If yes, Could you give me some suggestions to find methods so that I can achieve this goal?
> 
> Any help is much appreciated:)

different people have different step length and frequency，and their height is different.there are two way to re_id ,one is traditional solution,and the other one is deep learning,mostly people like the second one these years.i hope these can help you .

**Comment by akamob** [comment]
Hi, @xerifg, Thank you very much for your reply.
Yes, I have read related papers of gait recognition and person re-id. Gait recognition usually use GEI as its feature and wear smartwatch or cell phone to record person pose. Person re-id usually related to DeepSORT.

Based on my application (use keypoints of human body for gait recognition to distinguish human identity.), it's hard to find the related open source resources. I found [this](https://www.youtube.com/watch?v=BPi5zK2GBho) video but I'm not sure how to achieve it.

I would be grateful if you could give me some ideas:)
Thank you!
